### ISSUE TITLE
Implement Global Exception Handler

### ISSUE THREAD

**Issue by mokhs00** [BOAZ-LKVK/dittodining-server#3]
### Summary

- 현재 적절한 기능을 포함한 global exception handler가 존재하지 않아서 개발 필요
- 아래와 같은 기능 필요
  - error 응답 구조화 -> json 형식으로
  - etc...

### 중요 포인트

- 현재 fiber를 server framework으로 쓰고 있는데 fiber에서 제공하는 hander의 구조를 잘 이해하고 적용하는 것이 필요

**Comment by falconlee236** [comment]
이거를 건드려보면서 이해를 해야지 transaction 쪽도 건들 수 있을거 같아서 이거부터 해보겠습니다 @mokhs00

**Comment by falconlee236** [comment]
error handler랑 custom error 만들어서 해보기. fiber에 있는 error handler를 사용해 보자.
